'use strict';

const path = require('node:path');
const { nativeImage } = require('electron');

/**
 * Stamps "Generated by GD Suits" on a rendered image.
 *
 * This is done here, after the image exists, rather than by asking the model
 * to draw it. Image models are unreliable at text - they misspell it, move it,
 * and sometimes paint it into the cloth - and whatever they drew would be
 * baked into the render, so refining that render would feed the garbled mark
 * back in. Stamping afterwards gives the same mark in the same place every
 * time, and the render on disk stays clean for the next refinement.
 *
 * Only renders are ever stamped. A client's own photograph or a reference
 * picture from a magazine is not "generated by GD Suits", and saying so on it
 * would be false. That decision is made by the caller, against the database,
 * not by anything the interface asks for.
 */

const BADGE_PATH = path.join(__dirname, 'assets', 'render-badge.png');
const WATERMARK_PATH = path.join(__dirname, 'assets', 'render-watermark.png');

// Share of the image width the badge takes, and its distance from the edge.
const WIDTH_SHARE = 0.34;
const MARGIN_SHARE = 0.025;
// Below this the words stop being readable, so the badge grows instead.
const MIN_BADGE_WIDTH = 140;

// The watermark across the middle. The corner badge says who made the picture;
// this says it again where a crop cannot take it off, which is the whole point
// of a proof mark. Faint enough that the cloth is still the thing being judged
// - at a tenth it reads at arm's length and disappears when you look at a lapel.
const WATERMARK_WIDTH_SHARE = 0.62;
const WATERMARK_ALPHA = 0.1;
// Mean brightness above which the mark is painted dark instead of light.
const LIGHT_BACKGROUND = 140;

function load(file, what) {
  const image = nativeImage.createFromPath(file);
  if (image.isEmpty()) throw new Error(`The render ${what} is missing from the app.`);
  return image;
}
let badgeImage = null;
function badge() {
  if (!badgeImage) badgeImage = load(BADGE_PATH, 'badge');
  return badgeImage;
}
let watermarkImage = null;
function watermark() {
  if (!watermarkImage) watermarkImage = load(WATERMARK_PATH, 'watermark');
  return watermarkImage;
}

/**
 * Returns PNG bytes of `buffer` with the badge in the bottom-right corner.
 *
 * Bitmaps from nativeImage are BGRA and, for anything decoded from a PNG,
 * premultiplied - measured, not assumed: white at 50% alpha comes back as
 * 128,128,128,128. So the blend is premultiplied "source over": the badge's
 * colour is added as-is and the image beneath is scaled by what the badge
 * leaves uncovered. The straight-alpha formula would darken every soft edge.
 */
/**
 * Premultiplied "source over", in place: each badge pixel is added as it is,
 * and whatever it sits on is kept in proportion to what the badge leaves
 * uncovered. Both bitmaps are BGRA. Pixels outside `dst` are skipped, so a
 * badge wider than the image cannot write past the end of the buffer.
 */
function blendInto(dst, width, height, src, bw, bh, x0, y0) {
  for (let y = 0; y < bh; y++) {
    const dy = y0 + y;
    if (dy < 0 || dy >= height) continue;
    for (let x = 0; x < bw; x++) {
      const dx = x0 + x;
      if (dx < 0 || dx >= width) continue;
      const s = (y * bw + x) * 4;
      const a = src[s + 3];
      if (a === 0) continue;
      const d = (dy * width + dx) * 4;
      const keep = 255 - a;
      for (let c = 0; c < 4; c++) {
        const top = c === 3 ? a : src[s + c];
        dst[d + c] = Math.min(255, top + Math.round((dst[d + c] * keep) / 255));
      }
    }
  }
  return dst;
}

/**
 * The mean brightness of the part of the image a mark is about to cover,
 * every `step`th pixel. Only that part: a render is a man against a backdrop,
 * and averaging the whole picture would let a dark suit decide the tone of a
 * mark lying on a pale wall.
 */
function meanBrightness(dst, width, height, x0, y0, w, h, step = 4) {
  let total = 0, count = 0;
  for (let y = Math.max(0, y0); y < Math.min(height, y0 + h); y += step) {
    for (let x = Math.max(0, x0); x < Math.min(width, x0 + w); x += step) {
      const i = (y * width + x) * 4;
      total += 0.0722 * dst[i] + 0.7152 * dst[i + 1] + 0.2126 * dst[i + 2];
      count++;
    }
  }
  return count === 0 ? 255 : total / count;
}

/**
 * Which tiles of the region a mark is about to cover are light.
 *
 * The mark is toned per tile rather than per image, because a render is a man
 * against a backdrop and one wordmark crosses both: a single tone would put
 * half of it where it cannot be seen. Per pixel would be finer still and
 * wrong - a letter crossing a lapel would flicker tone along the weave. A tile
 * is about the width of a stroke, so a letter changes tone once, at the edge.
 */
const TILE = 24;
function lightTiles(dst, width, height, x0, y0, bw, bh, tile = TILE) {
  const cols = Math.ceil(bw / tile), rows = Math.ceil(bh / tile);
  const light = new Uint8Array(cols * rows);
  for (let r = 0; r < rows; r++) {
    for (let c = 0; c < cols; c++) {
      const mean = meanBrightness(dst, width, height, x0 + c * tile, y0 + r * tile, tile, tile, 3);
      light[r * cols + c] = mean > LIGHT_BACKGROUND ? 1 : 0;
    }
  }
  return { light, cols, tile };
}

/**
 * Blends the watermark in, faded to `alpha` and dark or light per tile.
 *
 * Both are one multiplication because the bitmap is premultiplied and the file
 * is pure white - b, g and r all equal the alpha, which make-marks.js checks
 * every time it draws it. Fading is scaling all four channels; going dark is
 * keeping the alpha and setting the colour to nothing. Neither needs to know
 * anything about the shape of the letters.
 */
function blendWatermark(dst, width, height, src, bw, bh, x0, y0, alpha, tiles) {
  for (let y = 0; y < bh; y++) {
    const dy = y0 + y;
    if (dy < 0 || dy >= height) continue;
    const row = Math.floor(y / tiles.tile) * tiles.cols;
    for (let x = 0; x < bw; x++) {
      const dx = x0 + x;
      if (dx < 0 || dx >= width) continue;
      const s = (y * bw + x) * 4;
      if (src[s + 3] === 0) continue;
      const a = Math.round(src[s + 3] * alpha);
      if (a === 0) continue;
      const colour = tiles.light[row + Math.floor(x / tiles.tile)] ? 0 : a;
      const d = (dy * width + dx) * 4;
      const keep = 255 - a;
      for (let c = 0; c < 4; c++) {
        const top = c === 3 ? a : colour;
        dst[d + c] = Math.min(255, top + Math.round((dst[d + c] * keep) / 255));
      }
    }
  }
  return dst;
}

/** Resized marks, so a page of renders at one size resizes each mark once. */
const RESIZED_LIMIT = 6;
const resized = new Map();
function resizedMark(image, key, options) {
  if (resized.has(key)) return resized.get(key);
  const mark = image.resize({ ...options, quality: 'best' });
  const entry = { bitmap: mark.toBitmap(), ...mark.getSize() };
  resized.set(key, entry);
  if (resized.size > RESIZED_LIMIT) resized.delete(resized.keys().next().value);
  return entry;
}

/**
 * Lays the watermark across the middle of `dst`, in place, light or dark
 * according to what it finds there. Returns which it chose, for the tests.
 */
function stampWatermark(dst, width, height) {
  const source = watermark();
  const ratio = source.getSize().height / source.getSize().width;
  let w = Math.max(1, Math.round(width * WATERMARK_WIDTH_SHARE));
  let h = Math.max(1, Math.round(w * ratio));
  // A wide, short image - a swatch photographed on its side - would otherwise
  // get a mark taller than the picture.
  if (h > height * 0.6) {
    h = Math.max(1, Math.round(height * 0.6));
    w = Math.max(1, Math.round(h / ratio));
  }
  const { bitmap, width: bw, height: bh } = resizedMark(source, `wm:${w}`, { width: w });
  const x0 = Math.round((width - bw) / 2);
  const y0 = Math.round((height - bh) / 2);
  const tiles = lightTiles(dst, width, height, x0, y0, bw, bh);
  blendWatermark(dst, width, height, bitmap, bw, bh, x0, y0, WATERMARK_ALPHA, tiles);
  return { x0, y0, width: bw, height: bh, tiles };
}

function stamp(buffer, format = 'png') {
  const base = nativeImage.createFromBuffer(Buffer.from(buffer));
  if (base.isEmpty()) throw new Error('That file is not an image that can be stamped.');
  const { width, height } = base.getSize();

  const margin = Math.round(width * MARGIN_SHARE);
  let target = Math.round(Math.min(width * 0.9, Math.max(width * WIDTH_SHARE, MIN_BADGE_WIDTH)));
  let mark = badge().resize({ width: target, quality: 'best' });
  // A very wide, short image could leave the badge taller than the space.
  if (mark.getSize().height + margin * 2 > height) {
    mark = badge().resize({ height: Math.max(1, height - margin * 2), quality: 'best' });
    target = mark.getSize().width;
  }
  const { width: bw, height: bh } = mark.getSize();
  const x0 = Math.max(0, width - bw - margin);
  const y0 = Math.max(0, height - bh - margin);

  const dst = base.toBitmap();
  stampWatermark(dst, width, height);
  blendInto(dst, width, height, mark.toBitmap(), bw, bh, x0, y0);
  const out = nativeImage.createFromBitmap(dst, { width, height });
  return format === 'jpeg' ? out.toJPEG(92) : out.toPNG();
}

/**
 * The encoding a stamped copy should use. It matches the original file, so a
 * stamped render can sit under the same name - the exported client file links
 * to renders by filename, and a .jpg holding PNG bytes would be a lie.
 */
const formatFor = (filename) => (/\.jpe?g$/i.test(String(filename)) ? 'jpeg' : 'png');
const mimeFor = (format) => (format === 'jpeg' ? 'image/jpeg' : 'image/png');

/**
 * Renders never change once written - a refinement is a new file - so a
 * stamped copy can be kept and reused. Bounded, because each entry is a full
 * image and the tailor may page through dozens.
 */
const CACHE_LIMIT = 12;
const cache = new Map();
function stampCached(key, buffer, format = 'png') {
  if (cache.has(key)) {
    const hit = cache.get(key);
    cache.delete(key);
    cache.set(key, hit);
    return hit;
  }
  const out = stamp(buffer, format);
  cache.set(key, out);
  if (cache.size > CACHE_LIMIT) cache.delete(cache.keys().next().value);
  return out;
}

module.exports = {
  stamp, stampCached, blendInto, blendWatermark, stampWatermark, lightTiles, meanBrightness,
  formatFor, mimeFor, BADGE_PATH, WATERMARK_PATH,
};
