'use strict';

const path = require('node:path');
const { nativeImage } = require('electron');

/**
 * Stamps "Generated by GD Suits" on a rendered image.
 *
 * This is done here, after the image exists, rather than by asking the model
 * to draw it. Image models are unreliable at text - they misspell it, move it,
 * and sometimes paint it into the cloth - and whatever they drew would be
 * baked into the render, so refining that render would feed the garbled mark
 * back in. Stamping afterwards gives the same mark in the same place every
 * time, and the render on disk stays clean for the next refinement.
 *
 * Only renders are ever stamped. A client's own photograph or a reference
 * picture from a magazine is not "generated by GD Suits", and saying so on it
 * would be false. That decision is made by the caller, against the database,
 * not by anything the interface asks for.
 */

const BADGE_PATH = path.join(__dirname, 'assets', 'render-badge.png');

// Share of the image width the badge takes, and its distance from the edge.
const WIDTH_SHARE = 0.34;
const MARGIN_SHARE = 0.025;
// Below this the words stop being readable, so the badge grows instead.
const MIN_BADGE_WIDTH = 140;

let badgeImage = null;
function badge() {
  if (!badgeImage) {
    badgeImage = nativeImage.createFromPath(BADGE_PATH);
    if (badgeImage.isEmpty()) throw new Error('The render badge is missing from the app.');
  }
  return badgeImage;
}

/**
 * Returns PNG bytes of `buffer` with the badge in the bottom-right corner.
 *
 * Bitmaps from nativeImage are BGRA and, for anything decoded from a PNG,
 * premultiplied - measured, not assumed: white at 50% alpha comes back as
 * 128,128,128,128. So the blend is premultiplied "source over": the badge's
 * colour is added as-is and the image beneath is scaled by what the badge
 * leaves uncovered. The straight-alpha formula would darken every soft edge.
 */
/**
 * Premultiplied "source over", in place: each badge pixel is added as it is,
 * and whatever it sits on is kept in proportion to what the badge leaves
 * uncovered. Both bitmaps are BGRA. Pixels outside `dst` are skipped, so a
 * badge wider than the image cannot write past the end of the buffer.
 */
function blendInto(dst, width, height, src, bw, bh, x0, y0) {
  for (let y = 0; y < bh; y++) {
    const dy = y0 + y;
    if (dy < 0 || dy >= height) continue;
    for (let x = 0; x < bw; x++) {
      const dx = x0 + x;
      if (dx < 0 || dx >= width) continue;
      const s = (y * bw + x) * 4;
      const a = src[s + 3];
      if (a === 0) continue;
      const d = (dy * width + dx) * 4;
      const keep = 255 - a;
      for (let c = 0; c < 4; c++) {
        const top = c === 3 ? a : src[s + c];
        dst[d + c] = Math.min(255, top + Math.round((dst[d + c] * keep) / 255));
      }
    }
  }
  return dst;
}

function stamp(buffer, format = 'png') {
  const base = nativeImage.createFromBuffer(Buffer.from(buffer));
  if (base.isEmpty()) throw new Error('That file is not an image that can be stamped.');
  const { width, height } = base.getSize();

  const margin = Math.round(width * MARGIN_SHARE);
  let target = Math.round(Math.min(width * 0.9, Math.max(width * WIDTH_SHARE, MIN_BADGE_WIDTH)));
  let mark = badge().resize({ width: target, quality: 'best' });
  // A very wide, short image could leave the badge taller than the space.
  if (mark.getSize().height + margin * 2 > height) {
    mark = badge().resize({ height: Math.max(1, height - margin * 2), quality: 'best' });
    target = mark.getSize().width;
  }
  const { width: bw, height: bh } = mark.getSize();
  const x0 = Math.max(0, width - bw - margin);
  const y0 = Math.max(0, height - bh - margin);

  const dst = base.toBitmap();
  blendInto(dst, width, height, mark.toBitmap(), bw, bh, x0, y0);
  const out = nativeImage.createFromBitmap(dst, { width, height });
  return format === 'jpeg' ? out.toJPEG(92) : out.toPNG();
}

/**
 * The encoding a stamped copy should use. It matches the original file, so a
 * stamped render can sit under the same name - the exported client file links
 * to renders by filename, and a .jpg holding PNG bytes would be a lie.
 */
const formatFor = (filename) => (/\.jpe?g$/i.test(String(filename)) ? 'jpeg' : 'png');
const mimeFor = (format) => (format === 'jpeg' ? 'image/jpeg' : 'image/png');

/**
 * Renders never change once written - a refinement is a new file - so a
 * stamped copy can be kept and reused. Bounded, because each entry is a full
 * image and the tailor may page through dozens.
 */
const CACHE_LIMIT = 12;
const cache = new Map();
function stampCached(key, buffer, format = 'png') {
  if (cache.has(key)) {
    const hit = cache.get(key);
    cache.delete(key);
    cache.set(key, hit);
    return hit;
  }
  const out = stamp(buffer, format);
  cache.set(key, out);
  if (cache.size > CACHE_LIMIT) cache.delete(cache.keys().next().value);
  return out;
}

module.exports = { stamp, stampCached, blendInto, formatFor, mimeFor, BADGE_PATH };
