'use strict';

/**
 * Validation for everything crossing the IPC boundary.
 *
 * The renderer is untrusted, so values arriving from it are checked here
 * rather than assumed. This is both a security control - it stops a
 * compromised renderer reaching outside its lane - and a correctness one:
 * a malformed id should fail loudly instead of corrupting a client file.
 */

class ValidationError extends Error {
  constructor(message) {
    super(message);
    this.name = 'ValidationError';
    this.code = 'invalid_input';
  }
}

const fail = (what) => {
  throw new ValidationError(what);
};

/** A database row id: a positive, safe integer. */
function id(value, field = 'id') {
  const n = Number(value);
  if (!Number.isSafeInteger(n) || n <= 0) fail(`${field} must be a positive whole number`);
  return n;
}

function optionalId(value, field = 'id') {
  return value === undefined || value === null ? null : id(value, field);
}

function str(value, field, max = 500) {
  if (value === undefined || value === null) return '';
  if (typeof value !== 'string') fail(`${field} must be text`);
  if (value.length > max) fail(`${field} is too long (max ${max} characters)`);
  return value;
}

function oneOf(value, allowed, field) {
  const v = str(value, field, 80);
  if (v && !allowed.includes(v)) fail(`${field} must be one of: ${allowed.join(', ')}`);
  return v;
}

function num(value, field, { min = -1e9, max = 1e9 } = {}) {
  if (value === undefined || value === null || value === '') return null;
  const n = Number(value);
  if (!Number.isFinite(n)) fail(`${field} must be a number`);
  if (n < min || n > max) fail(`${field} must be between ${min} and ${max}`);
  return n;
}

/**
 * A stored media filename. These are generated by the app, never typed, so
 * anything that does not match the generated shape is rejected outright -
 * which also makes path traversal impossible before it reaches the filesystem.
 */
const FILENAME = /^[a-z0-9_]+-[a-z0-9]+-[a-f0-9]+\.(jpg|jpeg|png|webp|heic|gif)$/i;

function filename(value, field = 'filename') {
  const v = str(value, field, 200);
  if (!FILENAME.test(v)) fail(`${field} is not a valid stored media filename`);
  return v;
}

/**
 * The token that ties the four views of one render together.
 *
 * Supplied by the renderer, which is the only place that knows the four calls
 * were one press. It is a label on rows the caller already owns and nothing
 * is looked up by it across an ownership boundary - but it is still checked,
 * because a value that reaches a database column unexamined is a habit worth
 * not having.
 */
const BATCH = /^[A-Za-z0-9-]{1,64}$/;

function batchId(value, field = 'batchId') {
  if (value === undefined || value === null || value === '') return null;
  const v = str(value, field, 64);
  if (!BATCH.test(v)) fail(`${field} is not a valid render batch`);
  return v;
}

/** A media scope folder: `project-12` or `client-3`. */
const SCOPE = /^(project|client)-\d+$/;

function scope(value, field = 'scope') {
  const v = str(value, field, 60);
  if (!SCOPE.test(v)) fail(`${field} is not a valid media scope`);
  return v;
}

/** Images are capped so a runaway renderer cannot exhaust the disk. */
const MAX_IMAGE_BYTES = 12 * 1024 * 1024;
const IMAGE_MIMES = ['image/jpeg', 'image/jpg', 'image/png', 'image/webp', 'image/gif', 'image/heic'];

function dataUrl(value, field = 'image') {
  if (typeof value !== 'string') fail(`${field} must be a data URL`);
  const match = /^data:([a-z0-9.+/-]+);base64,/i.exec(value);
  if (!match) fail(`${field} must be a base64 data URL`);
  if (!IMAGE_MIMES.includes(match[1].toLowerCase())) fail(`${field} must be an image (got ${match[1]})`);

  const approxBytes = Math.floor(((value.length - match[0].length) * 3) / 4);
  if (approxBytes > MAX_IMAGE_BYTES) {
    fail(`${field} is too large (${Math.round(approxBytes / 1e6)}MB, limit ${MAX_IMAGE_BYTES / 1e6}MB)`);
  }
  return value;
}

/**
 * The spec and analysis blobs are free-form by design, so they are bounded by
 * total size rather than by shape.
 */
function jsonBlob(value, field, maxBytes = 256 * 1024) {
  if (value === undefined) return undefined;
  if (value === null || typeof value !== 'object') fail(`${field} must be an object`);
  const size = JSON.stringify(value).length;
  if (size > maxBytes) fail(`${field} is too large (${size} bytes, limit ${maxBytes})`);
  return value;
}

/** A Gemini model name, which becomes part of a request URL. */
function modelName(value, field = 'model') {
  const v = str(value, field, 120);
  if (v && !/^[a-zA-Z0-9._-]+$/.test(v)) fail(`${field} contains characters that are not allowed`);
  return v;
}

const PHOTO_SLOTS = ['front', 'side', 'back', 'face', 'fabric', 'lining', 'lining_collage', 'inspiration', 'fitting'];
const GARMENTS = ['jacket', 'waistcoat', 'pants', 'shirt', ''];
const REFERENCE_KINDS = ['style', 'fabric', 'lining', 'fit'];
const PROJECT_STATUSES = [
  'first_consultation', 'ready_first_fitting', 'ready_final_fit', 'completed_due', 'completed_paid','enquiry', 'quoted', 'deposit_paid', 'in_production', 'first_fitting', 'alterations', 'final_fitting', 'delivered', 'draft', 'approved'];
const PAYMENT_KINDS = ['deposit', 'balance', 'part_payment', 'refund'];
const ALTERATION_STATUSES = ['received', 'in_progress', 'ready', 'collected', 'cancelled'];
const EXTRA_STATUSES = ['ordered', 'received', 'fitted', 'delivered', 'cancelled'];
const FITTING_KINDS = ['first', 'final', 'extra'];

module.exports = {
  ValidationError,
  id, optionalId, str, oneOf, num,
  filename, scope, dataUrl, jsonBlob, modelName, batchId,
  PHOTO_SLOTS, GARMENTS, REFERENCE_KINDS, PROJECT_STATUSES, FITTING_KINDS,
  PAYMENT_KINDS, ALTERATION_STATUSES, EXTRA_STATUSES,
  MAX_IMAGE_BYTES,
};
