import React, { useState } from 'react';
import { api, messageFor } from '../lib/api.js';
import { useToast } from './ui.jsx';

/**
 * Saves a copy of an image the tailor is looking at.
 *
 * Nothing is moved or used up by a download, so the same image can be saved
 * again whenever it is wanted. `src` is the gdmedia:// address already on
 * screen; the main process works out where the bytes live and whether the
 * image is a render, and renders leave with the "Generated by GD Suits" badge.
 * Nothing here can choose where the file goes - the save dialog does.
 *
 * `chip` is the small overlay used on thumbnails.
 */
export default function DownloadButton({ src, name, chip = false, className = '', label = 'Download' }) {
  const [busy, setBusy] = useState(false);
  const toast = useToast();
  if (!src) return null;

  async function save(e) {
    // Thumbnails open or select on click; saving must not do that as well.
    e.preventDefault();
    e.stopPropagation();
    setBusy(true);
    try {
      const res = await api.media.download({ url: src, name });
      if (res?.saved) toast(`Saved ${res.name}`, 'ok');
    } catch (err) {
      toast(messageFor(err), 'err');
    } finally {
      setBusy(false);
    }
  }

  if (chip) {
    return (
      <button
        type="button"
        className={`dl-chip ${className}`}
        onClick={save}
        disabled={busy}
        title="Download"
        aria-label={`Download ${name || 'image'}`}
      >
        {busy ? '…' : '↓'}
      </button>
    );
  }
  return (
    <button type="button" className={`btn ${className}`} onClick={save} disabled={busy}>
      {busy ? 'Saving…' : label}
    </button>
  );
}
