/**
 * Regenerates the two marks stamped on every rendered image that leaves the
 * app: the badge in the corner, and the watermark across the middle.
 *
 *   npm run make:marks
 *
 * Kept as a script rather than two mystery binaries so the marks can be
 * changed and rebuilt the same way. They are drawn by Chromium from HTML at
 * several times the size they will be shown, and scaled down per image.
 *
 * The lettering follows the GD Suits logo: wide-tracked capitals in a serif,
 * the way "SUITS" and "A STYLE TAILORED FOR YOU" are set on it. The earlier
 * badge was mixed-case and read as a caption from some other company.
 *
 * The badge's ground is light on purpose: the left half of the GD symbol is
 * charcoal, and on a dark badge it would disappear.
 *
 * The watermark is pure white on transparent, and nothing else. Not a style
 * choice - brand.js decides per image whether the mark should be light or
 * dark, and turning white into dark is zeroing three channels. Any other
 * colour in the file would make that impossible.
 */
const { app, BrowserWindow } = require('electron');
const fs = require('fs');
const os = require('os');
const path = require('path');

const symbol = fs.readFileSync(path.join(__dirname, '../src/assets/symbol.png')).toString('base64');
const OUT_DIR = path.join(__dirname, '../electron/assets');

const SERIF = `'Iowan Old Style', 'Palatino Linotype', Palatino, Georgia, serif`;

const badgeHtml = `<!doctype html><html><head><meta charset="utf-8"><style>
  html, body { margin: 0; background: transparent; }
  .badge {
    display: inline-flex; align-items: center; gap: 36px;
    padding: 30px 54px 30px 44px; border-radius: 999px;
    background: rgba(252, 250, 245, 0.93);
    box-shadow: inset 0 0 0 3px rgba(201, 162, 39, 0.55);
  }
  img { height: 118px; display: block; }
  .t { font-family: ${SERIF}; font-size: 62px; line-height: 1; white-space: nowrap;
       text-transform: uppercase; }
  .by { color: #4a443c; letter-spacing: 9px; }
  .name { color: #8a6d14; letter-spacing: 13px; font-size: 68px; margin-left: 40px; }
</style></head><body>
  <div class="badge">
    <img src="data:image/png;base64,${symbol}">
    <div class="t"><span class="by">Generated by</span><span class="name">GD Suits</span></div>
  </div>
</body></html>`;

/**
 * The lockup sits on one line, like the logo: the symbol, then the name in
 * tracked capitals. The `brightness(0) invert(1)` filter paints every opaque
 * pixel of the symbol pure white and leaves its alpha alone, so the two-tone
 * symbol becomes the silhouette the watermark needs.
 */
const watermarkHtml = `<!doctype html><html><head><meta charset="utf-8"><style>
  html, body { margin: 0; background: transparent; }
  .mark { display: inline-flex; align-items: center; gap: 44px; padding: 16px; }
  img { height: 190px; display: block; filter: brightness(0) invert(1); }
  .t { font-family: ${SERIF}; font-size: 150px; line-height: 1; white-space: nowrap;
       text-transform: uppercase; letter-spacing: 26px; color: #ffffff; }
</style></head><body>
  <div class="mark"><img src="data:image/png;base64,${symbol}"><div class="t">GD Suits</div></div>
</body></html>`;

// Both marks are drawn in one window, loaded one after the other. A second
// offscreen window refuses to load anything at all - data: URL or file, the
// same ERR_FAILED - so there is only ever one.
const TMP = fs.mkdtempSync(path.join(os.tmpdir(), 'gd-marks-'));
let win = null;

async function draw(html, selector, file, width, height) {
  const page = path.join(TMP, file.replace('.png', '.html'));
  fs.writeFileSync(page, html);
  if (!win) {
    win = new BrowserWindow({
      width: 2600, height: 600, show: false, transparent: true, frame: false,
      backgroundColor: '#00000000', webPreferences: { offscreen: true },
    });
  }
  win.setSize(width, height);
  await win.loadFile(page);
  const rect = JSON.parse(await win.webContents.executeJavaScript(`
    document.fonts.ready.then(() => {
      const r = document.querySelector('${selector}').getBoundingClientRect();
      return JSON.stringify({ x: Math.floor(r.x), y: Math.floor(r.y), width: Math.ceil(r.width), height: Math.ceil(r.height) });
    })`));
  await new Promise((r) => setTimeout(r, 400));
  const image = await win.webContents.capturePage(rect);
  const out = path.join(OUT_DIR, file);
  fs.writeFileSync(out, image.toPNG());
  return { rect, bitmap: image.toBitmap(), out };
}

app.whenReady().then(async () => {
  const badge = await draw(badgeHtml, '.badge', 'render-badge.png', 2400, 400);
  console.log(`wrote ${path.relative(process.cwd(), badge.out)}  ${badge.rect.width}x${badge.rect.height}`);
  console.log(`  corner pixel alpha (should be 0, the pill is rounded): ${badge.bitmap[3]}`);

  const wm = await draw(watermarkHtml, '.mark', 'render-watermark.png', 2600, 500);
  console.log(`wrote ${path.relative(process.cwd(), wm.out)}  ${wm.rect.width}x${wm.rect.height}`);
  // Every pixel of the watermark must be white or nothing, because brand.js
  // tones it by zeroing colour. Premultiplied, white means b=g=r=a.
  let offWhite = 0;
  for (let i = 0; i < wm.bitmap.length; i += 4) {
    const a = wm.bitmap[i + 3];
    if (a === 0) continue;
    if (wm.bitmap[i] !== a || wm.bitmap[i + 1] !== a || wm.bitmap[i + 2] !== a) offWhite++;
  }
  console.log(`  pixels that are not white (should be 0): ${offWhite}`);
  fs.rmSync(TMP, { recursive: true, force: true });
  app.exit(offWhite === 0 ? 0 : 1);
}).catch((e) => { console.error(e); app.exit(1); });
