/**
 * Regenerates electron/assets/render-badge.png, the mark stamped on every
 * rendered image that leaves the app.
 *
 * Kept as a script rather than a mystery binary so the badge can be changed
 * and rebuilt the same way. It is drawn by Chromium from HTML, in the app's
 * own serif, at several times the size it will be shown and scaled down per
 * image when stamped.
 *
 *   npx electron scripts/make-badge.js
 *
 * The ground is light on purpose: the left half of the GD symbol is charcoal,
 * and on a dark badge it would disappear.
 */
const { app, BrowserWindow } = require('electron');
const fs = require('fs');
const path = require('path');

const symbol = fs.readFileSync(path.join(__dirname, '../src/assets/symbol.png')).toString('base64');
const OUT = path.join(__dirname, '../electron/assets/render-badge.png');

const html = `<!doctype html><html><head><meta charset="utf-8"><style>
  html, body { margin: 0; background: transparent; }
  .badge {
    display: inline-flex; align-items: center; gap: 34px;
    padding: 30px 60px 30px 44px; border-radius: 999px;
    background: rgba(252, 250, 245, 0.93);
    box-shadow: inset 0 0 0 3px rgba(201, 162, 39, 0.55);
  }
  img { height: 118px; display: block; }
  .t { font-family: 'Iowan Old Style', 'Palatino Linotype', Palatino, Georgia, serif;
       font-size: 76px; line-height: 1; white-space: nowrap; color: #1c1a17; letter-spacing: 0.3px; }
  .t b { color: #8a6d14; font-weight: 700; }
</style></head><body>
  <div class="badge"><img src="data:image/png;base64,${symbol}"><div class="t">Generated by <b>GD Suits</b></div></div>
</body></html>`;

app.whenReady().then(async () => {
  const win = new BrowserWindow({
    width: 1800, height: 400, show: false, transparent: true, frame: false,
    backgroundColor: '#00000000', webPreferences: { offscreen: true },
  });
  await win.loadURL('data:text/html;base64,' + Buffer.from(html).toString('base64'));
  const rect = JSON.parse(await win.webContents.executeJavaScript(`
    document.fonts.ready.then(() => {
      const r = document.querySelector('.badge').getBoundingClientRect();
      return JSON.stringify({ x: Math.floor(r.x), y: Math.floor(r.y), width: Math.ceil(r.width), height: Math.ceil(r.height) });
    })`));
  await new Promise((r) => setTimeout(r, 400));
  const image = await win.webContents.capturePage(rect);
  fs.writeFileSync(OUT, image.toPNG());
  const bmp = image.toBitmap();
  console.log(`wrote ${path.relative(process.cwd(), OUT)}  ${rect.width}x${rect.height}`);
  console.log(`corner pixel alpha (should be 0, the pill is rounded): ${bmp[3]}`);
  app.exit(0);
});
